services:
  db:
    container_name: postgres
    image: postgres:17.4
    environment:
      # https://www.postgresql.org/docs/current/libpq-envars.html
      - PGHOST=${DATABASE_HOST}
      - PGPORT=${DATABASE_PORT}
      - PGUSER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
